### ISSUE TITLE
Implement site_unique in more places

### ISSUE THREAD

**Issue by tomsaleeba** [ternaustralia/ausplotsR#2]
Currently we build the `site_unique` field on the client side at https://github.com/ternaustralia/ausplotsR/blob/5b4d4d969762a12c41809dc1af190ebb881fe279/R/get_ausplots.R#L110 and also on line 127.

This could be built on the server side and just served up on the client side. This isn't that important, but I think adding the field in more places *is* important.

The field could also be included in the veg_voucher, veg_pi and veg_basal responses to make it easier for consumers to join (merge?) data frames.

**Comment by GregGuerin** [comment]
It's a fairly fast operation so not urgent to move to server side, although that could be implemented later.

Agreed, adding the unique survey ID combination to each table where it is currently missing would make sense.

**Comment by GregGuerin** [comment]
Presently, 'site_unique' field is created for all 3 raw veg tables in 'get_auplots' at lines 100, 127 and 157.

Site and visit #.1 ID fields are returned in the site info table but not combined (easy to add that).

At present, none of the 3 soil tables, nor the veg structural summary table, are returned from the server with a site visit #.ID field, only a site location name - so that would need to be added on the server side either way.

**Comment by GregGuerin** [comment]
In the Site_unique branch have now implemented creation of the 'site_unique' field in those tables where it was missing - site info, structural summaries and the 3 soil tables. However, the 'site_location_visit_id' field is not currently returned from the database for structural summaries and soils; as soon as that is added we can test out. Have also updated outputs of fractional_cover post-processing function to include site_unique for ease of merging back with other site data.

**Comment by tomsaleeba** [comment]
I've made sure that `site_location_visit_id` and `site_location_name` are present in all responses.

**Comment by GregGuerin** [comment]
Looks good.
