### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by stew822** [ternaustralia/ausplotsR#47]
Hi there,

Thought I'd flag the following issue:

This package has been archived from CRAN because dependency has also been archived:
https://cran.r-project.org/web/packages/ausplotsR/index.html

I cannot install from GitHub due to same issue.

Kind regards
Stewart

**Comment by GregGuerin** [comment]
Thank you.

we are working to resolve whether the archived dependency will be reinstated (preferred) or we will have to code in the functionality directly in the ausplotsR package.

In the meantime, work arounds are:

1. download the latest archived ausplotsR version tarball from CRAN and install locally (See archived link on CRAN ausplotsR page)
 
Package simba can also be accessed from the CRAN archive as tarball, i.e. latest archived version.

2. Install ausplotsR via GitHub and set 'dependencies = FALSE' in the devtools::install_github() call so that no attempt is made to automatically install all the dependencies, which you can install manually/separately

simba also has a GitHub version: https://github.com/cran/simba - try installing that or the archived CRAN tarball first, and then install archived of git version of ausplotsR.

Hope to be back up and running on CRAN soon - hopefully these work arounds will help for now.

Greg

**Comment by GregGuerin** [comment]
Many pages, but here is one suggestion for installing a downloaded tar.gz package (as you can download from the archive page of each package):

https://stackoverflow.com/questions/1474081/how-do-i-install-an-r-package-from-source

Link to ausplotsR tarballs to download:

https://cran.r-project.org/src/contrib/Archive/ausplotsR/

Cheers
